### ISSUE TITLE
Scoreboard text in old versions per line could be longer

### ISSUE THREAD

**Issue by SerendipityR-2022** [andrei1058/BedWars1058#1008]
Sorry for my poor english. I noticed that the scoreboard text can only display 32 words per line now, but in fact it can display up to 48 words per line even if in old versions.

That's because the code in `com.andrei1058.bedwars.libs.sidebar.v1_8_R3.SidebarImpl` or other nms class (<1.13) only use the prefix prop to show the 16 words of the beginning 16 words, and the suffix prop for the other 16 words. 

However, we can also use the entryname to display 16 words, so that we can totally display 48 words.
16 (prefix) + 16 (entry) + 16 (suffix) = 48
It's a great improvement, and we can display more informations to players without add more new scoreboard lines.

There are examples working in different old versions, it perfectly displays up to 48 words per line.
https://gist.github.com/zyuiop/8fcf2ca47794b92d7caa

I know that you may busy in processing other works, planning to drop the support of v1_8_R3, but i sincerely hope that you can take this request into consideration before you do that.

**Comment by andrei1058** [comment]
Bedwars1058 makes use of [SidebarLib ](https://github.com/andrei1058/SidebarLib)which I confirm, does not use entity names in scoreboards. We are not going to achieve that because line identifiers are based on chat colors then used as entity names. I originally decided to do that in order to make it use less cpu and send less packets to the client. I do not want to destroy teams every time the line is updated. I gave a quick look at your link and it seems to have the same problematic. Using entity names is better when lines are not dynamic and frequently updated.

**Comment by SerendipityR-2022** [comment]
Okay, thanks for your help!
