### ISSUE TITLE
Bug entering the room in spectore form

### ISSUE THREAD

**Issue by StrikDev1909** [andrei1058/BedWars1058#111]
This error is common in multiarena when a game room has just started, you can enter the room and exit quickly and there will be a bug, this error can kill players and destroy the map.

**Comment by reussy** [comment]
Please update with the template: 

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**System (please complete the following information):**
 - OS: [e.g. iOS]
 - Server software [e.g. spigot, paper]
 - Server Version [e.g. 1.8.8]
 - Plugin Version [e.g. 21.10.1]

**Additional context**
Add any other context about the problem here.

**Comment by ajgeiss0702** [comment]
If you do not, this issue will be ignored. Same with your other issues which you still have not updated.

**Comment by StrikDev1909** [comment]
Desbribe the bug:
Spectator can break and hit playing players in a arenas.

Reproduce:
1. Open map selector
2. Spec a running arenas.
3. When join spectator do /leave quickly
4. Ok, you can break the map.

Screenshots 
![image](https://user-images.githubusercontent.com/93809658/142951852-e16b22c1-58c7-404b-8049-9f7902014175.png)


OS: windows 10
Server Sofware: PaperSpigot 1.12.2
Plugin Version: 21.11.1
