### ISSUE TITLE
New placeholder Which returns Maps name Instead of its display-name. {MapName}

### ISSUE THREAD

**Issue by ghost** [andrei1058/BedWars1058#153]
Please add map name placeholder to bedwars plugin. which shows the map that you use for bedwars instead of display name.

**Comment by reussy** [comment]
Please update with the template

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.

**Comment by ghost** [comment]
Make a placeholder that returns the map name instead of arena name

**Comment by ghost** [comment]
Consider this is map name-
![image](https://user-images.githubusercontent.com/93807992/145675331-6509d3c4-9f97-4869-b537-5fce922b387a.png)
And this is ArenaName- 
![image](https://user-images.githubusercontent.com/93807992/145675348-5173de07-f795-4a1f-a9c3-35d2b7ec9761.png)

I want a placeholder that returns the Maps name Instead of ArenaName/DisplayName like for example {Arena}

**Comment by ghost** [comment]
Bedwars1058 returns {MAP} as DisplayName
I want another placeholder which returns Maps name which is used as The world for bedwars game.
