### ISSUE TITLE
Lore Placeholders

### ISSUE THREAD

**Issue by AstroLands** [andrei1058/BedWars1058#154]
Is your feature request related to a problem? Please describe.
Placeholder isnt loading on Items lores

Describe the solution you'd like
Supporting Placeholders on on Items Lores in Lobby

Describe alternatives you've considered
I dont think there's alternatives

Additional context
Nope

**Comment by reussy** [comment]
Please, update with the template

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.
