### ISSUE TITLE
MapReset And Game Start High Ticks

### ISSUE THREAD

**Issue by TheWylot** [andrei1058/BedWars1058#166]
**Describe the bug**
BedWars1058 have a lot of ticks specially on map start and reset arena with Bukkit World Manager & SlimeWorldManager

**Expected behavior**
Recode the Map Reset and Start System. it's need a highly optimize.

**System (please complete the following information):**
 - OS: Windows Server 2019
 - Server software: Paper
 - Server Version: 1.8.8
 - Plugin Version: 21.11.1

**Comment by andrei1058** [comment]
we need your hardware specs

**Comment by TheWylot** [comment]
20x Core I9 10850K 3.60ghz
64GB Ram DDR4 3200mhz
1TB NVME

**Comment by andrei1058** [comment]
And how many things are you hosting on it? Please also provide java version and timings.

**Comment by TheWylot** [comment]
33 Plugins 
Java Version 11 and
how can i send u timings private ?

**Comment by andrei1058** [comment]
_And how many things are you hosting on it?_

**Comment by TheWylot** [comment]
u mean servers ?

**Comment by TheWylot** [comment]
@andrei1058 ?

**Comment by andrei1058** [comment]
I mean servers and other software that is using resources

**Comment by TheWylot** [comment]
> I mean servers and other software that is using resources

we are hosting 2 server on it 
1 bedwars with 100-150 players per day
1 survival 1.16.5 with 70 players per day
the cpu usage is 10%-20% with 200 players hosting

**Comment by andrei1058** [comment]
welp, if the usage gets up to 20%, I guess you should allocate more resources to the bedwars server?! I guess it's limited or something

**Comment by ItzZisker** [comment]
steps to fix your problem:

**step 1:** don't use windows server, it's garbage.
**step 2:** use bungee mode with autoscale true, multiarena can't handle up to 100 200 players, even if you have a very good cpu, you need to allocate more ram, when you do that, the garbage collector will need more cpu resources in order to perform garbage collection, and everytime a garbage collection executes, your cpu usage will rise. bungee is more handy and you need also a connection management + cluster system on your server in order to make it stable for 200+ players.
**question:** you were talking about your superplugin1058 fork, what was the meaning of async world generation? lmao, i wonder how thread-safe it is.
