### ISSUE TITLE
Cant Pickup Items (rare bug)

### ISSUE THREAD

**Issue by lunoxxofficial** [andrei1058/BedWars1058#520]
Sometimes when we join into the arena and game starts we cant pickup items in the generator , We have to simply jump into the void and die to us to pick it up. 
I think this the reason is we cant pick items in lobby and somehow it bugs and won't let us pick items from the ground. 
**To Reproduce**
Steps to reproduce the behavior
We cannot pourposly reproduce this , this only happenes one in 20 games or less.
Proof 
https://media.discordapp.net/attachments/348088106546757653/975777098394402866/unknown.png

**Comment by IIHERO4** [comment]
Hi, I faced the same issue on the server im working for. The issue seemed to be fixed once they respawn. a fix was adding the same change (in respawn code) to the beginning of the game.
![image](https://user-images.githubusercontent.com/46909116/170822556-64ab0d6a-9fe1-4a80-a87d-b6c192dc928e.png)

You can add it yourself because pull requests tend take a lot of time to be reviewed/merged
