### ISSUE TITLE
Tools dont have unbreaking after upgrading

### ISSUE THREAD

**Issue by Eradiator** [andrei1058/BedWars1058#625]
1. Make all the swords unbreakable by default.
2. Make ladder cost 4 for 8
3. Make Bridge egg cost 1 for 1
4. Make chainmail cost 30

**Comment by tomkeuper** [comment]
1. Can confirm the upgraded tools dont have unbreaking on them and will break over time.
![image](https://user-images.githubusercontent.com/29728836/216842750-db3fc926-072b-430e-a6a5-2abfd4be159f.png)

2/3/4 are configurable in the config so it will be best to just change that on a server level instead of updating the plugin for that.

I will make this issue as a bug related to point 1

**Comment by tomkeuper** [comment]
Duplicate of #603

**Comment by tomkeuper** [comment]
Issue will be picked up in different issue
