### ISSUE TITLE
Altough more of a question, am i able to make a specific player break blocks in the lobby?

### ISSUE THREAD

**Issue by whatthexampp** [andrei1058/BedWars1058#630]
Hi,

I'd like to edit the SlimeWorldManager map, without re-creating everything. 
Even though i am an OP, i am not able to break blocks. Is there a permission or a way to make my self able to break blocks, also without restarting the server?

**Comment by tomkeuper** [comment]
No there is no permission to change blocks in an arena thats mainly becuase the plugin basically creates a copy of the map and every time the arena gets played the backup gets put back thus resetting the arena because of this structure its basically not possible to just save a map if you want to make changes.
What you could do i create a copy of the map you want to change and give it a new version live *_v2 and just copying the arena config if no locations have changed. Im quite sure that bigger servers do the same, also to prevent accidental changes or rogue staff members who secretly hide stuff in lobbies

**Comment by tomkeuper** [comment]
Im closing this request as this is wont be implemented with the current setup, and there doesnt seem to be a lot of people asking for this feature.
