### ISSUE TITLE
Level placeholder in lobby not showing correctly

### ISSUE THREAD

**Issue by cjtganzon** [andrei1058/BedWars1058#661]
**Describe the bug**

The level placeholder on the scoreboard in the lobby only shows the number
**To Reproduce**
1. Install bedwars1058 23.2 with the default config.
2. Go to the server and look at the scoreboard.
3. Look at Your Level and just see a number

**Expected behavior**

The placeholder should show the level with a star next to it surrounded by brackets like this: [1✩]
It works in chat but not on the scoreboard
**Screenshots**

![image](https://user-images.githubusercontent.com/62964779/216919252-b3c2eaeb-1da2-4eee-a0e4-e0ddf1a035cb.png)

**System (please complete the following information):**
 - OS: Windows 11
 - Server software: Purpur 
 - Server Version: 1.19.3
 - Plugin Version: 23.2 

**Additional context**

**Comment by tomkeuper** [comment]
I noticed that the placeholder provder has changed in the latest release but im not sure if this was intentional or not. But I do think that its best this way as the plain number is better for manipulation afterwards. So that would mean that you would have to add it mannually. Just put [{level}✩] in your language files

@andrei1058 Shall I add the original [{level}✩] text to all the level placeholders in the default language files?

**Comment by tomkeuper** [comment]
I looked into this issue a bit further and it does seem to be an issue with the plugin. The level support should take the level config and check what color the star should be etc. I will try to fix it later on.

**Comment by tomkeuper** [comment]
Seem to have fixed this issue. I am not sure what exactly changed and how it did work before and suddenly stopped working. It looks like the same code was implented.

**Comment by tomkeuper** [comment]
Will be fixed in the next release. Thanks for reporting!
