### ISSUE TITLE
23.1 and newer doesn't work with bedwarsproxy.

### ISSUE THREAD

**Issue by BranGamingMC** [andrei1058/BedWars1058#666]
So basically I have an issue with the version of the plugin: 23.1 and newer.
I downgraded it for now to 22.7 because that works.

When I join the game using BedWarsProxy I join the game but it kicks me out immediately.

Things I have tried:
 - deleting all plugins in the bedwars solo game server.
 - deleting all of the plugins in bedwars proxy server.

System:
 - Server software pandaspigot
 - Server Version 1.8.8

Logs:

[22:23:05 INFO]: UUID of player debran is a97da3bd-0f2e-4819-83a7-ceb688cc5bba
[22:23:06 INFO]: debran[/] logged in with entity id 441 at ([bw_temp_y23m02d09g18]0.5, 145.0, 0.5)
[22:23:07 INFO]: [BW1058-WinStreak DEBUG]: Successfully PlayerJoinEvent. debran's streak cache was loaded.
[22:23:07 INFO]: debran lost connection: Disconnected
[22:23:07 INFO]: [BW1058-WinStreak DEBUG]: Successfully PlayerQuitEvent. debran's profile cache was saved and destroyed.

**Comment by BranGamingMC** [comment]
Forgot to paste the BedWarsProxy Logs.

i used /bwmenu solo but i tried /bw gui to and nothing different

Logs:

[22:27:42 INFO]: [BW1058-WinStreak DEBUG]: Successfully PlayerJoinEvent. debran's streak cache was loaded.
[22:27:44 INFO]: debran issued server command: /bwmenu solo
[22:27:45 INFO]: debran lost connection: Disconnected
[22:27:45 INFO]: [BW1058-WinStreak DEBUG]: Successfully PlayerQuitEvent. debran's profile cache was saved and destroyed.

**Comment by tomkeuper** [comment]
Can you post a bit more of the logs as this is just BW Winstreak debug. And maybe bungeecord logs aswell

**Comment by BranGamingMC** [comment]
BungeeCord logs: https://pastebin.com/x2BwxWRN

Bedwars game server logs: https://pastebin.com/mh7XfNUH

I probably leaked a lot of things.

**Comment by tomkeuper** [comment]
![image](https://user-images.githubusercontent.com/29728836/218219277-8339cc63-f8eb-4989-92d6-34f711cf15c4.png)
When playing with anything lower than 1.19

**Comment by HEMO313** [comment]
> ![image](https://user-images.githubusercontent.com/29728836/218219277-8339cc63-f8eb-4989-92d6-34f711cf15c4.png) When playing with anything lower than 1.19

same problem here

**Comment by Chromaah** [comment]
There is a workaround to this issue. If you dont believe me, it worked for me and like 10 other people.

Simply just turn all the 'player-list:' formating to false.
The Image below shows how it looks by default. They all have to be set to false
![Screenshot_3](https://user-images.githubusercontent.com/123222872/218570659-23a7d2bf-b669-4ed7-a7c6-0483c2c09611.png)

**Comment by joohnaquino** [comment]
> There is a workaround to this issue. If you dont believe me, it worked for me and like 10 other people.
> 
> Simply just turn all the 'player-list:' formating to false. The Image below shows how it looks by default. They all have to be set to false
![Screenshot_3](https://user-images.githubusercontent.com/123222872/218570659-23a7d2bf-b669-4ed7-a7c6-0483c2c09611.png)

As I said on Discord, this is being caused by another reason. This is just one of the solutions, which may cause some problems for some people.


> ![image](https://user-images.githubusercontent.com/29728836/218219277-8339cc63-f8eb-4989-92d6-34f711cf15c4.png) When playing with anything lower than 1.19

This is being caused by a spelling error on the part of BW1058, not versions or anything like that.


The problem is being caused by a misspelling in:
![image](https://user-images.githubusercontent.com/120399502/219732672-c1cd6da5-a848-465e-974e-8f3ab2865436.png)
See that "TeamName/Color", "Team" has its initial letter **"T"** in uppercase, while in the lang (messages_en.yml) the initial letter **T** is in lowercase **"t "**
![image](https://user-images.githubusercontent.com/120399502/219734378-215cab0c-0f66-40ba-83de-ec9ae6dd085a.png)


A brief (perhaps simple) solution for this would be for BW1058 to ignore whether it is in lowercase or UPPERCASE, I'm not a dev but I know that this can obviously cause some problems, but I think possibly not, as long as it respects the "rule" of being inside {teamcolor/name/letter}
This is not the first time this has happened to me, all my lang has already been deleted due to a spelling error that the plugin itself changes (which honestly seems to be caused on purpose by someone)


**UPDATE:**
Please, if this error still happens to you, please disable the features as @chromaah said, however you will be required to transfer this feature to your tab/nametag plugin, I strongly recommend using the [NEZNAMY TAB (link for bw1058 config)](https://github.com/NEZNAMY/TAB/wiki/Mini-guides-collection#bedwars1058-compatibility), this and other settings can be found in the [full wiki](https://github.com/NEZNAMY/TAB/wiki)

**Comment by andrei1058** [comment]
Should be fixed with https://github.com/andrei1058/SidebarLib/pull/17

**Comment by BranGamingMC** [comment]
the Chromaah  method worked by disabling but it kicks u out immediatly when the game ends.
I don't know how to use SidebarLib.
