### ISSUE TITLE
cant hear block sound

### ISSUE THREAD

**Issue by probro248** [andrei1058/BedWars1058#779]
when i place a block i cant hear the block sound

**Comment by probro248** [comment]
when i place a block i cant hear the block sound

**Comment by Chromaah** [comment]
thats an unfixable issue with viaversion and players on 1.8

this is NOT a bedwars issue!

**Comment by andrei1058** [comment]
It usually happens when you switch the server version and the configuration being generated for the first server it runs on is no longer compatible with the new version, that means you just need to configure them better. Try reading on the wiki https://wiki.andrei1058.dev/docs/BedWars1058/configuration/sounds-configuration
